name: flutter_app_user
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  go_router: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Icon.png
    - assets/images/Online.png
    - assets/images/Child.png
    - assets/images/Partner.png
    - assets/images/Process.png
    - assets/images/Account.png
    - assets/images/Background.png
    - assets/images/Card-2.png

    - assets/images/home/Auto.svg
    - assets/images/home/Bike.svg
    - assets/images/home/House.svg
    - assets/images/home/House.svg
    - assets/images/home/Personal.svg
    - assets/images/home/Private.svg
    - assets/images/home/Travel.svg
    - assets/images/home/Coin.png
    - assets/images/home/Document.png
    - assets/images/home/Product.png
    - assets/images/home/Product_2.png
